name: Backend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: Chat.Api
      run: docker build . -t kova98k/chat:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: kova98k
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push kova98k/chat:latest

    - name: Pull the image to VM and start it
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: kova98k
        key: ${{ secrets.SSH_KEY }}
        script: | 
          docker pull kova98k/chat:latest
          docker stop chat || true
          docker rm chat || true
          docker run -d -p 9001:5001 --restart always --name chat kova98k/chat:latest
